name: Update abbreviations.json

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        curl "$src" |  jq 'del(.[] | select(. | match("\\$CURSOR")))' \
          > data/abbreviations.json
      env:
        src: https://raw.githubusercontent.com/leanprover/vscode-lean4/master/lean4-unicode-input/src/abbreviations.json

    - uses: peter-evans/create-pull-request@v4
      with:
        title: 'Update abbreviations.json'
        commit-message: 'chore: update abbreviations.json'
        branch: update-abbreviations
        labels: automation,update
        
